version: 0.0.0.29

filters:
  preparinglevel:
    method: simple
    pattern: Preparing level
    to-console: false
    to-standard-log: false
    log-path: ''
    replace-string: ''
    replace-tokens: ''
