name: Calm
version: 0.0.0.24
author: Feaelin <feaelin@kemenel.org>
description: 'C.A.L.M.: Console And Log Management'

load: STARTUP
main: org.ruhlendavis.mc.calm.Calm

commands:
  calm:
    description: Gateway to all Calm commands.
  calmreload:
    description: Reloads Calm's configuration from disk.
    permission: calm.reload
    permission-message: "§cYou do not have access to that command."

permissions:
